image: node:20

pipelines:
  branches:
    main:
      - step:
          name: Deploy to Vercel
          caches:
            - node
          script:
            - npm install
            - CI=false npm run build
            - npm install -g vercel
            - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
            - vercel deploy --prod --token=$VERCEL_TOKEN