import type { Severity } from "./detection";

export type EntityKind = "person" | "asset" | "vehicle";
export type PersonStatus = "active" | "watchlist" | "cleared";
export type AssetStatus = "normal" | "flagged" | "missing";
export type VehicleStatus = "normal" | "flagged" | "suspicious";

export interface EntityTimelineEntry {
  id: string;
  time: string;
  date: string;
  dateDisplay: string;
  eventType: string;
  location: string;
  confidence: number;
  severity: Severity;
  site: string;
  siteDisplay: string;
  camera: string;
  caseId?: string;
  isCrossSite?: boolean;
  crossSiteConfidence?: number;
  note?: string;
}

export interface EntityLinkedCase {
  id: string;
  title: string;
  severity: Severity;
  status: string;
  assignee: string;
  eventCount: number;
}

/**
 * A suggested adaptive-identity merge surfaced by the ReID engine.
 * Generated by comparing historical embeddings + feature patterns across detections —
 * a low direct-recognition score may still trigger a similarity-analysis suggestion
 * that the operator can approve to merge IDs together.
 */
export interface PossibleIdentityMatch {
  /** ID of the candidate the system thinks this entity may be the same as. */
  candidateId: string;
  candidateLabel: string;
  /** Overall similarity score (0-100). */
  similarity: number;
  /** Confidence threshold — when below this, the system flagged as ambiguous and split. */
  reasonLabel: "Significant appearance change" | "Partial occlusion" | "Lighting difference" | "Accessories changed" | "Hairstyle changed";
  /** Per-feature similarity breakdown, e.g. face: 88, body: 81, gait: 74. */
  features: { label: string; score: number }[];
  /** Where the candidate was last seen (cross-site or cross-area context). */
  candidateLastSeen: string;
  candidateSitesObserved: string[];
  /** Number of historical detections on the candidate side. */
  candidateDetections: number;
  /** First seen ISO timestamp of the candidate. */
  candidateFirstSeenDisplay: string;
}

export interface PersonEntity {
  kind: "person";
  id: string;
  name: string;
  identified: boolean;
  status: PersonStatus;
  statusLabel: string;
  firstSeen: string;
  lastSeen: string;
  lastSeenAgo: string;
  sitesObserved: string[];
  totalDetections: number;
  linkedCases: EntityLinkedCase[];
  reIdConfidence: number;
  credentialMatches: number;
  priorEventCount: number;
  timeline: EntityTimelineEntry[];
  possibleMatches?: PossibleIdentityMatch[];
}

export interface AssetEntity {
  kind: "asset";
  id: string;
  type: string;
  category: string;
  lastService: string;
  identified: boolean;
  status: AssetStatus;
  statusLabel: string;
  sitesObserved: string[];
  totalIncidents: number;
  reIdConfidence?: number;
  priorEventCount?: number;
  credentialMatches?: number;
  linkedCases: EntityLinkedCase[];
  timeline: EntityTimelineEntry[];
}

export interface VehicleEntity {
  kind: "vehicle";
  id: string;
  plate?: string;
  vehicleType: string;
  color?: string;
  registeredTo?: string;
  identified: boolean;
  status: VehicleStatus;
  statusLabel: string;
  sitesObserved: string[];
  totalIncidents: number;
  reIdConfidence?: number;
  priorEventCount?: number;
  credentialMatches?: number;
  linkedCases: EntityLinkedCase[];
  timeline: EntityTimelineEntry[];
}

export type AnyEntity = PersonEntity | AssetEntity | VehicleEntity;
